from .main_menu import MainMenu
from .base_tab import BaseTab
from .summary_tab import SummaryTab
from .scatter_tab import ScatterTab
from .events_tab import EventsTab
from .csv_tab import CSVTab
from .data_view import DataView
from .scrape_menu import ScrapeMenu
from .logs_window import LogsWindow
from .profile_menu import ProfileMenu
from .settings_menu import SettingsMenu
from .utils import open_file
