from .CSVTab_ui import Ui_CSVTab
from .DataView_ui import Ui_DataView
from .EventsTab_ui import Ui_EventsTab
from .LogsWindow_ui import Ui_LogsWindow
from .MainMenu_ui import Ui_MainMenu
from .MainWindow_ui import Ui_MainWindow
from .ProfileMenu_ui import Ui_ProfileMenu
from .ScatterTab_ui import Ui_ScatterTab
from .ScrapeMenu_ui import Ui_ScrapeMenu
from .SettingsMenu_ui import Ui_SettingsMenu
from .SummaryTab_ui import Ui_SummaryTab
