# Form implementation generated from reading ui file 'c:\Users\Caden\Desktop\nhtsa-scrape\src\app\ui\CSVTab.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CSVTab(object):
    def setupUi(self, CSVTab):
        CSVTab.setObjectName("CSVTab")
        CSVTab.resize(551, 386)
        self.gridLayout = QtWidgets.QGridLayout(CSVTab)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(parent=CSVTab)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 1)
        self.saveBtn = QtWidgets.QPushButton(parent=CSVTab)
        self.saveBtn.setObjectName("saveBtn")
        self.gridLayout.addWidget(self.saveBtn, 0, 0, 1, 1)

        self.retranslateUi(CSVTab)
        QtCore.QMetaObject.connectSlotsByName(CSVTab)

    def retranslateUi(self, CSVTab):
        _translate = QtCore.QCoreApplication.translate
        CSVTab.setWindowTitle(_translate("CSVTab", "Form"))
        self.saveBtn.setText(_translate("CSVTab", "Save Data to CSV"))
