# Form implementation generated from reading ui file 'c:\Users\Caden\Desktop\nhtsa-scrape\src\app\ui\DataView.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DataView(object):
    def setupUi(self, DataView):
        DataView.setObjectName("DataView")
        DataView.resize(880, 609)
        self.verticalLayout = QtWidgets.QVBoxLayout(DataView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topHLayout = QtWidgets.QHBoxLayout()
        self.topHLayout.setObjectName("topHLayout")
        self.exitBtn = QtWidgets.QPushButton(parent=DataView)
        self.exitBtn.setObjectName("exitBtn")
        self.topHLayout.addWidget(self.exitBtn)
        self.mainTitle = QtWidgets.QLabel(parent=DataView)
        self.mainTitle.setObjectName("mainTitle")
        self.topHLayout.addWidget(self.mainTitle)
        self.topHLayout.setStretch(0, 1)
        self.topHLayout.setStretch(1, 4)
        self.verticalLayout.addLayout(self.topHLayout)
        self.tabWidget = QtWidgets.QTabWidget(parent=DataView)
        self.tabWidget.setObjectName("tabWidget")
        self.dataTab = QtWidgets.QWidget()
        self.dataTab.setObjectName("dataTab")
        self.gridLayout = QtWidgets.QGridLayout(self.dataTab)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(parent=self.dataTab)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(parent=self.dataTab)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 2, 0, 1, 1)
        self.tabWidget.addTab(self.dataTab, "")
        self.casesTab = QtWidgets.QWidget()
        self.casesTab.setObjectName("casesTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.casesTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listView = QtWidgets.QListView(parent=self.casesTab)
        self.listView.setObjectName("listView")
        self.gridLayout_2.addWidget(self.listView, 0, 0, 1, 1)
        self.eventViewLayout = QtWidgets.QGridLayout()
        self.eventViewLayout.setObjectName("eventViewLayout")
        self.eventLabel = QtWidgets.QLabel(parent=self.casesTab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventLabel.sizePolicy().hasHeightForWidth())
        self.eventLabel.setSizePolicy(sizePolicy)
        self.eventLabel.setObjectName("eventLabel")
        self.eventViewLayout.addWidget(self.eventLabel, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.eventViewLayout, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.tabWidget.addTab(self.casesTab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(DataView)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(DataView)

    def retranslateUi(self, DataView):
        _translate = QtCore.QCoreApplication.translate
        DataView.setWindowTitle(_translate("DataView", "Form"))
        self.exitBtn.setText(_translate("DataView", "Exit"))
        self.mainTitle.setText(_translate("DataView", "Data Viewer"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.dataTab), _translate("DataView", "Data")
        )
        self.eventLabel.setText(_translate("DataView", "Some event"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.casesTab), _translate("DataView", "Cases")
        )
