# Form implementation generated from reading ui file 'c:\Users\Caden\Desktop\nhtsa-scrape\src\app\ui\EventsTab.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EventsTab(object):
    def setupUi(self, EventsTab):
        EventsTab.setObjectName("EventsTab")
        EventsTab.resize(465, 329)
        self.horizontalLayout = QtWidgets.QHBoxLayout(EventsTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.eventsList = QtWidgets.QListView(parent=EventsTab)
        self.eventsList.setMinimumSize(QtCore.QSize(100, 0))
        self.eventsList.setObjectName("eventsList")
        self.horizontalLayout.addWidget(self.eventsList)
        self.eventLayout = QtWidgets.QGridLayout()
        self.eventLayout.setObjectName("eventLayout")
        self.label = QtWidgets.QLabel(parent=EventsTab)
        self.label.setObjectName("label")
        self.eventLayout.addWidget(
            self.label,
            0,
            0,
            1,
            1,
            QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignVCenter,
        )
        self.horizontalLayout.addLayout(self.eventLayout)

        self.retranslateUi(EventsTab)
        QtCore.QMetaObject.connectSlotsByName(EventsTab)

    def retranslateUi(self, EventsTab):
        _translate = QtCore.QCoreApplication.translate
        EventsTab.setWindowTitle(_translate("EventsTab", "Events"))
        self.label.setText(_translate("EventsTab", "Select an event to view."))
