# Form implementation generated from reading ui file 'c:\Users\Caden\Desktop\nhtsa-scrape\src\app\ui\ExitDataViewDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ExitDialog(object):
    def setupUi(self, ExitDialog):
        ExitDialog.setObjectName("ExitDialog")
        ExitDialog.resize(445, 262)
        self.verticalLayout = QtWidgets.QVBoxLayout(ExitDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.promptLabel = QtWidgets.QLabel(parent=ExitDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.promptLabel.sizePolicy().hasHeightForWidth())
        self.promptLabel.setSizePolicy(sizePolicy)
        self.promptLabel.setObjectName("promptLabel")
        self.verticalLayout.addWidget(self.promptLabel)
        self.profileNameEdit = QtWidgets.QLineEdit(parent=ExitDialog)
        self.profileNameEdit.setObjectName("profileNameEdit")
        self.verticalLayout.addWidget(self.profileNameEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ExitDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Discard|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ExitDialog)
        self.buttonBox.accepted.connect(ExitDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ExitDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ExitDialog)

    def retranslateUi(self, ExitDialog):
        _translate = QtCore.QCoreApplication.translate
        ExitDialog.setWindowTitle(_translate("ExitDialog", "Dialog"))
        self.promptLabel.setText(_translate("ExitDialog", "Save Profile?"))
