# Form implementation generated from reading ui file 'c:\Users\Caden\Desktop\nhtsa-scrape\src\app\ui\LogsWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LogsWindow(object):
    def setupUi(self, LogsWindow):
        LogsWindow.setObjectName("LogsWindow")
        LogsWindow.resize(619, 419)
        self.verticalLayout = QtWidgets.QVBoxLayout(LogsWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logsEdit = QtWidgets.QTextEdit(parent=LogsWindow)
        self.logsEdit.setStyleSheet("background-color: black; color: white;")
        self.logsEdit.setReadOnly(True)
        self.logsEdit.setObjectName("logsEdit")
        self.verticalLayout.addWidget(self.logsEdit)
        self.bottomHLayout = QtWidgets.QHBoxLayout()
        self.bottomHLayout.setObjectName("bottomHLayout")
        self.clearBtn = QtWidgets.QPushButton(parent=LogsWindow)
        self.clearBtn.setObjectName("clearBtn")
        self.bottomHLayout.addWidget(self.clearBtn)
        self.saveBtn = QtWidgets.QPushButton(parent=LogsWindow)
        self.saveBtn.setObjectName("saveBtn")
        self.bottomHLayout.addWidget(self.saveBtn)
        self.verticalLayout.addLayout(self.bottomHLayout)

        self.retranslateUi(LogsWindow)
        QtCore.QMetaObject.connectSlotsByName(LogsWindow)

    def retranslateUi(self, LogsWindow):
        _translate = QtCore.QCoreApplication.translate
        LogsWindow.setWindowTitle(_translate("LogsWindow", "Scrape Tool Logs"))
        self.logsEdit.setHtml(_translate("LogsWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\';\"><br /></p></body></html>"))
        self.clearBtn.setText(_translate("LogsWindow", "Clear Logs"))
        self.saveBtn.setText(_translate("LogsWindow", "Save Logs"))
