# Form implementation generated from reading ui file 'c:\Users\Caden\Desktop\nhtsa-scrape\src\app\ui\LogsWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LogsWindow(object):
    def setupUi(self, LogsWindow):
        LogsWindow.setObjectName("LogsWindow")
        LogsWindow.resize(619, 419)
        self.verticalLayout = QtWidgets.QVBoxLayout(LogsWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logsEdit = QtWidgets.QTextEdit(parent=LogsWindow)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.logsEdit.setFont(font)
        self.logsEdit.setReadOnly(True)
        self.logsEdit.setObjectName("logsEdit")
        self.verticalLayout.addWidget(self.logsEdit)
        self.bottomHLayout = QtWidgets.QHBoxLayout()
        self.bottomHLayout.setObjectName("bottomHLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.bottomHLayout.addItem(spacerItem)
        self.saveBtn = QtWidgets.QPushButton(parent=LogsWindow)
        self.saveBtn.setObjectName("saveBtn")
        self.bottomHLayout.addWidget(self.saveBtn)
        self.bottomHLayout.setStretch(0, 1)
        self.bottomHLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.bottomHLayout)

        self.retranslateUi(LogsWindow)
        QtCore.QMetaObject.connectSlotsByName(LogsWindow)

    def retranslateUi(self, LogsWindow):
        _translate = QtCore.QCoreApplication.translate
        LogsWindow.setWindowTitle(_translate("LogsWindow", "Form"))
        self.saveBtn.setText(_translate("LogsWindow", "Save Logs"))
