# Form implementation generated from reading ui file 'c:\Users\Caden\Desktop\nhtsa-scrape\src\app\ui\MainMenu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(933, 596)
        self.gridLayout_2 = QtWidgets.QGridLayout(MainMenu)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.menuTitle = QtWidgets.QLabel(parent=MainMenu)
        self.menuTitle.setObjectName("menuTitle")
        self.verticalLayout.addWidget(self.menuTitle)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.scrapeBtn = QtWidgets.QPushButton(parent=MainMenu)
        self.scrapeBtn.setObjectName("scrapeBtn")
        self.verticalLayout.addWidget(self.scrapeBtn)
        self.openBtn = QtWidgets.QPushButton(parent=MainMenu)
        self.openBtn.setObjectName("openBtn")
        self.verticalLayout.addWidget(self.openBtn)
        self.logsBtn = QtWidgets.QPushButton(parent=MainMenu)
        self.logsBtn.setObjectName("logsBtn")
        self.verticalLayout.addWidget(self.logsBtn)
        self.settingsBtn = QtWidgets.QPushButton(parent=MainMenu)
        self.settingsBtn.setObjectName("settingsBtn")
        self.verticalLayout.addWidget(self.settingsBtn)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 2, 1, 1)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Form"))
        self.menuTitle.setText(_translate("MainMenu", "NHTSA Scraper Tool"))
        self.scrapeBtn.setText(_translate("MainMenu", "New Scrape"))
        self.openBtn.setText(_translate("MainMenu", "Open Existing Profile"))
        self.logsBtn.setText(_translate("MainMenu", "Open Application Logs"))
        self.settingsBtn.setText(_translate("MainMenu", "Settings"))
