# Form implementation generated from reading ui file 'c:\Users\Caden\Desktop\nhtsa-scrape\src\app\ui\ScatterTab.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ScatterTab(object):
    def setupUi(self, ScatterTab):
        ScatterTab.setObjectName("ScatterTab")
        ScatterTab.resize(504, 358)
        self.gridLayout_2 = QtWidgets.QGridLayout(ScatterTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.nassLabelBtn = QtWidgets.QPushButton(parent=ScatterTab)
        self.nassLabelBtn.setCheckable(True)
        self.nassLabelBtn.setChecked(True)
        self.nassLabelBtn.setObjectName("nassLabelBtn")
        self.gridLayout_2.addWidget(self.nassLabelBtn, 1, 1, 1, 1)
        self.totalDataBtn = QtWidgets.QPushButton(parent=ScatterTab)
        self.totalDataBtn.setCheckable(True)
        self.totalDataBtn.setObjectName("totalDataBtn")
        self.gridLayout_2.addWidget(self.totalDataBtn, 1, 2, 1, 1)
        self.nassDataBtn = QtWidgets.QPushButton(parent=ScatterTab)
        self.nassDataBtn.setCheckable(True)
        self.nassDataBtn.setChecked(True)
        self.nassDataBtn.setObjectName("nassDataBtn")
        self.gridLayout_2.addWidget(self.nassDataBtn, 1, 0, 1, 1)
        self.chartLayout = QtWidgets.QGridLayout()
        self.chartLayout.setObjectName("chartLayout")
        self.gridLayout_2.addLayout(self.chartLayout, 0, 0, 1, 4)
        self.totalLabelBtn = QtWidgets.QPushButton(parent=ScatterTab)
        self.totalLabelBtn.setEnabled(False)
        self.totalLabelBtn.setCheckable(True)
        self.totalLabelBtn.setChecked(True)
        self.totalLabelBtn.setObjectName("totalLabelBtn")
        self.gridLayout_2.addWidget(self.totalLabelBtn, 1, 3, 1, 1)

        self.retranslateUi(ScatterTab)
        QtCore.QMetaObject.connectSlotsByName(ScatterTab)

    def retranslateUi(self, ScatterTab):
        _translate = QtCore.QCoreApplication.translate
        ScatterTab.setWindowTitle(_translate("ScatterTab", "Scatterplot"))
        self.nassLabelBtn.setText(_translate("ScatterTab", "NASS_dv Case Labels"))
        self.totalDataBtn.setText(_translate("ScatterTab", "TOT_dv"))
        self.nassDataBtn.setText(_translate("ScatterTab", "NASS_dv"))
        self.totalLabelBtn.setText(_translate("ScatterTab", "TOT_dv Case Labels"))
