# Form implementation generated from reading ui file 'c:\Users\Caden\Desktop\nhtsa-scrape\src\app\ui\ScrapeMenu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ScrapeMenu(object):
    def setupUi(self, ScrapeMenu):
        ScrapeMenu.setObjectName("ScrapeMenu")
        ScrapeMenu.resize(1080, 720)
        self.verticalLayout = QtWidgets.QVBoxLayout(ScrapeMenu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topHLayout = QtWidgets.QHBoxLayout()
        self.topHLayout.setObjectName("topHLayout")
        self.backBtn = QtWidgets.QPushButton(parent=ScrapeMenu)
        self.backBtn.setObjectName("backBtn")
        self.topHLayout.addWidget(self.backBtn)
        self.mainTitle = QtWidgets.QLabel(parent=ScrapeMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainTitle.sizePolicy().hasHeightForWidth())
        self.mainTitle.setSizePolicy(sizePolicy)
        self.mainTitle.setObjectName("mainTitle")
        self.topHLayout.addWidget(self.mainTitle)
        self.verticalLayout.addLayout(self.topHLayout)
        self.body = QtWidgets.QGridLayout()
        self.body.setObjectName("body")
        self.verticalLayout.addLayout(self.body)
        self.bottomHLayout = QtWidgets.QHBoxLayout()
        self.bottomHLayout.setObjectName("bottomHLayout")
        self.moreBtn = QtWidgets.QLabel(parent=ScrapeMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moreBtn.sizePolicy().hasHeightForWidth())
        self.moreBtn.setSizePolicy(sizePolicy)
        self.moreBtn.setObjectName("moreBtn")
        self.bottomHLayout.addWidget(self.moreBtn)
        self.submitBtn = QtWidgets.QPushButton(parent=ScrapeMenu)
        self.submitBtn.setObjectName("submitBtn")
        self.bottomHLayout.addWidget(self.submitBtn)
        self.verticalLayout.addLayout(self.bottomHLayout)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(ScrapeMenu)
        QtCore.QMetaObject.connectSlotsByName(ScrapeMenu)

    def retranslateUi(self, ScrapeMenu):
        _translate = QtCore.QCoreApplication.translate
        ScrapeMenu.setWindowTitle(_translate("ScrapeMenu", "Form"))
        self.backBtn.setText(_translate("ScrapeMenu", "Back"))
        self.mainTitle.setText(_translate("ScrapeMenu", "New Scrape"))
        self.moreBtn.setText(_translate("ScrapeMenu", "More Options..."))
        self.submitBtn.setText(_translate("ScrapeMenu", "Scrape"))
