# Form implementation generated from reading ui file 'c:\Users\Caden\Desktop\nhtsa-scrape\src\app\ui\ScrapeMenu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ScrapeMenu(object):
    def setupUi(self, ScrapeMenu):
        ScrapeMenu.setObjectName("ScrapeMenu")
        ScrapeMenu.resize(1080, 720)
        self.verticalLayout = QtWidgets.QVBoxLayout(ScrapeMenu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topBarLayout = QtWidgets.QHBoxLayout()
        self.topBarLayout.setObjectName("topBarLayout")
        self.backBtn = QtWidgets.QPushButton(parent=ScrapeMenu)
        self.backBtn.setObjectName("backBtn")
        self.topBarLayout.addWidget(self.backBtn)
        self.menuTitle = QtWidgets.QLabel(parent=ScrapeMenu)
        self.menuTitle.setObjectName("menuTitle")
        self.topBarLayout.addWidget(self.menuTitle)
        self.verticalLayout.addLayout(self.topBarLayout)
        self.body = QtWidgets.QGridLayout()
        self.body.setObjectName("body")
        self.verticalLayout.addLayout(self.body)
        self.bottomBarLayout = QtWidgets.QHBoxLayout()
        self.bottomBarLayout.setObjectName("bottomBarLayout")
        self.expandBtn = QtWidgets.QLabel(parent=ScrapeMenu)
        self.expandBtn.setObjectName("expandBtn")
        self.bottomBarLayout.addWidget(self.expandBtn)
        self.submitBtn = QtWidgets.QPushButton(parent=ScrapeMenu)
        self.submitBtn.setObjectName("submitBtn")
        self.bottomBarLayout.addWidget(self.submitBtn)
        self.verticalLayout.addLayout(self.bottomBarLayout)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(ScrapeMenu)
        QtCore.QMetaObject.connectSlotsByName(ScrapeMenu)

    def retranslateUi(self, ScrapeMenu):
        _translate = QtCore.QCoreApplication.translate
        ScrapeMenu.setWindowTitle(_translate("ScrapeMenu", "Form"))
        self.backBtn.setText(_translate("ScrapeMenu", "Back"))
        self.menuTitle.setText(_translate("ScrapeMenu", "New Scrape"))
        self.expandBtn.setText(_translate("ScrapeMenu", "More Options..."))
        self.submitBtn.setText(_translate("ScrapeMenu", "Scrape"))
