# Form implementation generated from reading ui file 'c:\Users\Caden\Desktop\nhtsa-scrape\src\app\ui\SettingsMenu.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingsMenu(object):
    def setupUi(self, SettingsMenu):
        SettingsMenu.setObjectName("SettingsMenu")
        SettingsMenu.resize(711, 495)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsMenu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topHLayout = QtWidgets.QHBoxLayout()
        self.topHLayout.setObjectName("topHLayout")
        self.backBtn = QtWidgets.QPushButton(parent=SettingsMenu)
        self.backBtn.setObjectName("backBtn")
        self.topHLayout.addWidget(self.backBtn)
        self.mainTitle = QtWidgets.QLabel(parent=SettingsMenu)
        self.mainTitle.setObjectName("mainTitle")
        self.topHLayout.addWidget(self.mainTitle)
        self.topHLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.topHLayout)
        self.line = QtWidgets.QFrame(parent=SettingsMenu)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.bodyVLayout = QtWidgets.QVBoxLayout()
        self.bodyVLayout.setObjectName("bodyVLayout")
        self.debugBtn = QtWidgets.QPushButton(parent=SettingsMenu)
        self.debugBtn.setObjectName("debugBtn")
        self.bodyVLayout.addWidget(self.debugBtn)
        self.verticalLayout.addLayout(self.bodyVLayout)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(SettingsMenu)
        QtCore.QMetaObject.connectSlotsByName(SettingsMenu)

    def retranslateUi(self, SettingsMenu):
        _translate = QtCore.QCoreApplication.translate
        SettingsMenu.setWindowTitle(_translate("SettingsMenu", "Form"))
        self.backBtn.setText(_translate("SettingsMenu", "Back"))
        self.mainTitle.setText(_translate("SettingsMenu", "Scrape Settings"))
        self.debugBtn.setText(
            _translate("SettingsMenu", "Turn on DEBUG mode for logger")
        )
