# Form implementation generated from reading ui file 'c:\Users\Caden\Desktop\nhtsa-scrape\src\app\ui\SummaryTab.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SummaryTab(object):
    def setupUi(self, SummaryTab):
        SummaryTab.setObjectName("SummaryTab")
        SummaryTab.resize(608, 538)
        self.gridLayout = QtWidgets.QGridLayout(SummaryTab)
        self.gridLayout.setObjectName("gridLayout")
        self.openBtn = QtWidgets.QPushButton(parent=SummaryTab)
        self.openBtn.setObjectName("openBtn")
        self.gridLayout.addWidget(self.openBtn, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=SummaryTab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.paramsEdit = QtWidgets.QTextEdit(parent=self.groupBox)
        self.paramsEdit.setReadOnly(True)
        self.paramsEdit.setObjectName("paramsEdit")
        self.gridLayout_2.addWidget(self.paramsEdit, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(SummaryTab)
        QtCore.QMetaObject.connectSlotsByName(SummaryTab)

    def retranslateUi(self, SummaryTab):
        _translate = QtCore.QCoreApplication.translate
        SummaryTab.setWindowTitle(_translate("SummaryTab", "Form"))
        self.openBtn.setToolTip(_translate("SummaryTab", "Open directory containing raw data, images, etc."))
        self.openBtn.setText(_translate("SummaryTab", "Open Saved Data Location"))
        self.groupBox.setTitle(_translate("SummaryTab", "Scrape Params"))
